# Generated by Django 4.2 on 2025-06-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodssku',
            options={'verbose_name': '商品SKU', 'verbose_name_plural': '商品SKU'},
        ),
    ]
